### ISSUE TITLE
Panic after running DDT

### ISSUE THREAD

**Issue by skx** [ivanizag/iz-cpm#12]
First of all thank-you for sharing your code.  I've been slowly working on a CP/M emulator of my own over the past month or two - mine in golang, and I appreciate the comments you left in your code which were a helpful resource at times - to the extent I linked to your project from my README.

Anyway I figured I should finally actually test your project, and I found an interesting issue.  Sorry!

So I've put together a repository of "standard" software, much like you setup with your `download.sh` script.  My repository is here:

* https://github.com/skx/cpm-dist

Clone that to follow along.  My initial attempt was to compile a hello-world assembly-program, and run it:

```
$ RUST_BACKTRACE=1 ./iz-cpm --disk-a /home/skx/Repos/github.com/skx/cpm-dist/A/ --disk-b /home/skx/Repos/github.com/skx/cpm-dist/B/
iz-cpm https://github.com/ivanizag/iz-cpm
CP/M 2.2 Emulation
Press ctrl-c ctrl-c Y to return to host

A>asm hello
CP/M ASSEMBLER - VER 2.0
011B
000H USE FACTOR
END OF ASSEMBLY

A>load hello

FIRST ADDRESS 0100
LAST  ADDRESS 011A
BYTES READ    001B
RECORDS WRITTEN 01


A>hello

Hello, World!

```

Looks good.

Now I run `DDT.COM` and using that JUMP to address 0x0000, which is a boot:

```
A>ddt
DDT VERS 2.2
-g0000

A>asm hello             MI
Hello, World!
$
CP/M ASSEMBLER - VER 2.0
011B
000H USE FACTOR
END OF ASSEMBLY
```

Notice there that there is some `Hello, world!` output?  And yet the previous time we compiled that we just got the compilation as expected.

Let us try to load the `.COM` file from the generated `.HEX` - again starting from the top:

```
frodo ~/Downloads/iz-cpm-linux-v1.3.1 $ RUST_BACKTRACE=full ./iz-cpm --disk-a /home/skx/Repos/github.com/skx/cpm-dist/A/ --disk-b /home/skx/Repos/github.com/skx/cpm-dist/B/
iz-cpm https://github.com/ivanizag/iz-cpm
CP/M 2.2 Emulation
Press ctrl-c ctrl-c Y to return to host

A>asm hello
CP/M ASSEMBLER - VER 2.0
011B
000H USE FACTOR
END OF ASSEMBLY

A>load hello

FIRST ADDRESS 0100
LAST  ADDRESS 011A
BYTES READ    001B
RECORDS WRITTEN 01


A>ddt
DDT VERS 2.2
-g0000

A>asm hello             MI
Hello, World!
$
CP/M ASSEMBLER - VER 2.0
011B
000H USE FACTOR
END OF ASSEMBLY

A>load hello        :100100000E09110901CD0500C90D0A48656C6C6F17
:0B0110002C20576F726C64210D0A2434
:0000000000

thread 'main' panicked at src/bdos_environment.rs:107:19:
index out of bounds: the len is 16 but the index is 204
stack backtrace:
   0:     0x7f76720b52dc - std::backtrace_rs::backtrace::libunwind::trace::ha752d28ad8b59776
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f76720b52dc - std::backtrace_rs::backtrace::trace_unsynchronized::h19085f9ccfa8c39c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f76720b52dc - std::sys_common::backtrace::_print_fmt::h7fa8e07ec2f6097e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f76720b52dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf031f84ba50c0cfa
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f76720ea2e0 - core::fmt::rt::Argument::fmt::h41c4ec8113ce6748
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x7f76720ea2e0 - core::fmt::write::h9d6dcce53fee8498
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f76720b2fdf - std::io::Write::write_fmt::h1592172be29051fa
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x7f76720b50c4 - std::sys_common::backtrace::_print::h077b25e4211c79a3
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f76720b50c4 - std::sys_common::backtrace::print::h0992ac2bfe77cad2
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f76720b65d7 - std::panicking::default_hook::{{closure}}::h2cf07aea02dfbfab
  10:     0x7f76720b633f - std::panicking::default_hook::h85b79716976ec2d8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x7f76720b6a58 - std::panicking::rust_panic_with_hook::h8687ef8cbe256fb2
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x7f76720b693e - std::panicking::begin_panic_handler::{{closure}}::ha182011c2febc20e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x7f76720b57a6 - std::sys_common::backtrace::__rust_end_short_backtrace::h8ea229012037d9c8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x7f76720b66a2 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x7f7672012ae5 - core::panicking::panic_fmt::h4a1a6d8dbc505935
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x7f7672012ca2 - core::panicking::panic_bounds_check::h7ccafe65706d62d1
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:190:5
  17:     0x7f767201b8e2 - iz_cpm::bdos_environment::BdosEnvironment::get_directory::h47ac382745bda551
  18:     0x7f76720152c4 - iz_cpm::bdos_file::find_host_files::hc275de410d62360d
  19:     0x7f76720136bf - iz_cpm::bdos_file::open::h052ea4f54962a05d
  20:     0x7f767201cf9b - iz_cpm::bdos::Bdos::execute::hed741525d0a22a20
  21:     0x7f7672019ba4 - iz_cpm::main::hcddeec579b7c7c85
  22:     0x7f767201d2f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h54006916c45c37ab
  23:     0x7f767201cb19 - std::rt::lang_start::{{closure}}::he9f5b6b38ffdf303
  24:     0x7f76720ae96e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf47534de04578a83
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  25:     0x7f76720ae96e - std::panicking::try::do_call::he270afe99f162c7b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  26:     0x7f76720ae96e - std::panicking::try::hc551f5c5a344ecad
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  27:     0x7f76720ae96e - std::panic::catch_unwind::h6790e138972db2df
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  28:     0x7f76720ae96e - std::rt::lang_start_internal::{{closure}}::haa35f81c7641c384
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  29:     0x7f76720ae96e - std::panicking::try::do_call::h4e42cde918b15a44
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  30:     0x7f76720ae96e - std::panicking::try::hb3bfb1061a5e948b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  31:     0x7f76720ae96e - std::panic::catch_unwind::h4789ec49cbf5f558
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  32:     0x7f76720ae96e - std::rt::lang_start_internal::h141a6b3fc711a41c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  33:     0x7f767201cb0e - std::rt::lang_start::haf5dbd08b5b7a937


```

I'm not going to try to guess what is going on there, but it looks like the boot, via "JMP 0x0000" puts things into a bad state, after which there is oddity in many commands.

**Comment by ivanizag** [comment]
Wow. Thank you for the report, it doesn't look easy to find and come up with this clear repro steps.

The problem is that I was not resetting the reset vector at $0000 on warm boots as it is expected. Confirmed in http://www.gaby.de/cpm/manuals/archive/cpm22htm/ch6.htm table 6.5.

I hope you are learning and having fun with your CP/M emulator.

**Comment by skx** [comment]
Thanks for the quick fix, it looks like that explains everything :)

I'm learning and having fun, I guess I took the harder route as I try to emulate both the BIOS and the BDOS - the only binary I load is the user's program, or one of the available CCP images.

I see some minor differences in our support, I could report issues if you like, but otherwise we both seem to be similarly useful at running the major "real" programs.

**Comment by ivanizag** [comment]
The reports are always welcome. Please, just if it is not a burden for you.

Thanks!
